### ISSUE TITLE
Can't run Examples 

### ISSUE THREAD

**Issue by timotius02** [logotype/MyoJS#1]
I can't seem to run the Cubes, Gestures, or Minecraft examples on with or without a local server. What is the right way to run examples?

**Comment by fletchrichman** [comment]
This would be great to know the ideal way to run a local server!

**Comment by logotype** [comment]
Hi
These steps should work:
1. First and foremost, download "myodaemon" (https://github.com/logotype/myodaemon/blob/master/build/myodaemon.zip?raw=true) and run it, Mac OS X only for now.
2. Open any of the example HTML files in the examples/ folder, simply by double clicking them, you don't need a local server for this.
3. Examples should run without errors.

If any errors is happening, please let me know!
