### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by xtrimf** [logotype/MyoJS#4]
Hi,

I just got my Myo.
Trying to run your examples via local server, but nothing happens. (just saying "connecting...").
The Myo is synced and working fine.

what am I missing?

tnx

**Comment by logotype** [comment]
Hi

Just double checking, did you download myodaemon? It's required for the WebSocket communication between the Myo and the JS library, you can download it here, currently Mac OSX only:
https://github.com/logotype/myodaemon

BR,
Victor
