### ISSUE TITLE
Uncaught Error: Uncaught Error: Timestamp needs to be of type integer

### ISSUE THREAD

**Issue by decapyre** [logotype/MyoJS#5]
Getting this error on every frame event. Apparently `timestamp` is NaN sometimes.

Uncaught Error: Uncaught Error: Timestamp needs to be of type integer line 2040

**Comment by logotype** [comment]
Hi, I changed the timestamp datatype to be string instead. Let me know if that fixes the issue. For performance reasons, I don't parse it into a Date object. Please also update myodaemon.
