### ISSUE TITLE
Differences between MyoJS and the official myo.js?

### ISSUE THREAD

**Issue by dj-hedgehog** [logotype/MyoJS#6]
I've just started coding an Electron-application and want to add myo-support to it.
What are the differences between this package and the official myo.js bindings here: https://github.com/thalmiclabs/myo.js ?

**Comment by logotype** [comment]
Hi

Main differences are the way data is sent/received. The official library (myo.js) is sending individual events whereas MyoJS library is sending "frames" of data, which contains everything. MyoJS works the same as Leap Motion's API does.

I'd probably recommend using Myo's official library. It supports multiple Myo's, and is multi-platform.

BR,
Victor
